### ISSUE TITLE
Subscription support

### ISSUE THREAD

**Issue by SebStaeubert** [mosaic-hgw/ttp-fhir-ig#1]
Using subscription resources could help automate consent processing. E.g., if FHIR resources should only be transferred to a FHIR server when consent is pre-existing. Is something planned?
The question is asked on behalf of SMITH.

**Comment by mosaic-hgw** [comment]
- [ ]  @mosaic-hgw Antwort

**Comment by mosaic-hgw** [comment]
Wir planen die Umsetzung einer fTTP consent im Rahmen von NUM-RDP. Entsprechende subscription-Mechanismen werden wir bei der Umsetzung versuchen zu berücksichtigen. Danke für den Hinweis. Details hier: https://www.ths-greifswald.de/forscher/num/fttp-fact-sheet
