### ISSUE TITLE
Sammelticket / Kommentare

### ISSUE THREAD

**Issue by SebStaeubert** [mosaic-hgw/ttp-fhir-ig#10]
1. https://www.ths-greifswald.de/wp-content/uploads/tools/fhirgw/ig/ballot-fttp/ImplementationGuide-markdown-BeschreibungBallotFttp.html -> "prospektiv" würde ich streichen.
2. Link/Verweis zu NUM-RDP einfügen.
3. "Die fTTP Wahrscheinlichkeit ..." klingt merkwürdigt -> "Die Verfahren der fTTP ..." oder "Das Modul 'fTTP Wahrscheinlichkeit' ..." (falls das ein Eigenname ist).
4. https://www.ths-greifswald.de/wp-content/uploads/tools/fhirgw/ig/ballot-fttp/ImplementationGuide-markdown-WorkflowBasierteVerwaltung-ProfileUndExtensions.html -> Abschnitt "Extensions": Sollte hier nicht birthPlace, nationality und name.prefix beschrieben werden?
5. https://www.ths-greifswald.de/wp-content/uploads/tools/fhirgw/ig/ballot-fttp/ImplementationGuide-markdown-WorkflowBasierteVerwaltung-Operations-requestPsnWorkflow.html 
a) "studienspezifischen-Pseudonyme als Params." Params -> Parameter; 
b) "Der spezifizierte API-KEY muss valid sein" -> valide oder gültig
c) Invocations "This operation changes content" -> englisch? Das kommt mehrmals vor.

**Comment by mosaic-hgw** [comment]
1. typo ->fix
2. erstmal auf https://www.ths-greifswald.de/projekte/num-routine-data-platform/ verweisen, offizielle seite gibt es noch nicht
3. ja Eigenname, fix
4. ja, etwas uneindeutig: Für den Bereich Work... gibt es keine spezifischen Extensions. Es gelten aber die Extensions für das IDAT-Profil. IG wird angepasst.
5. a-b: Typo, c: Liegt am automatischen Simplifier-Rendering.
