### ISSUE TITLE
Kardinalität von `nationality`

### ISSUE THREAD

**Issue by makampf** [mosaic-hgw/ttp-fhir-ig#2]
`Patient.nationality` hat eine Kardinalität von 0..1, allerdings ist es durchaus möglich, mehrere Nationalitäten gleichzeitig oder hintereinander zu haben.  Für letzteres gibt es vmtl. auch das Feld `Patient.nationality.period`.
(Vgl. auch https://www.hl7.org/fhir/extension-patient-nationality.html)

**Comment by mosaic-hgw** [comment]
Edge-Case. Im Regelfall ist nur 1 Nationalität gegeben. fTTP und E-PIX würden hier, wenn tatsächlich Bedarf besteht, separate Identitäten verwenden.
