### ISSUE TITLE
Sammelticket FHIR IG gICS

### ISSUE THREAD

**Issue by SebStaeubert** [mosaic-hgw/ttp-fhir-ig#20]
- [Beschreibung](https://www.ths-greifswald.de/wp-content/uploads/tools/fhirgw/ig/ballot-gics/ImplementationGuide-markdown-BeschreibungBallotGics.html)
  - Abs.1 "... realen Versorgung" -> "Versorgung" oder "Patientenversorgung"
- [Einwilligungsmanagement](https://www.ths-greifswald.de/wp-content/uploads/tools/fhirgw/ig/ballot-gics/ImplementationGuide-markdown-Einwilligungsmanagement.html)
  - "der [AG Einwilligungsmanagement](https://simplifier.net/Einwilligungsmanagement)" -> "der HL7 [AG Einwilligungsmanagement](https://simplifier.net/Einwilligungsmanagement)"
  - "send bereitstellen zu können wurden" -> "send bereitstellen zu können, wurden"
  - Absatz "Übersicht der verfügbaren Operations" - warum ist genau dieser Absatz hier eingefügt und andere nicht, z.B. Profile und Ext. usw.?
  - [Profile und Extensions](https://www.ths-greifswald.de/wp-content/uploads/tools/fhirgw/ig/ballot-gics/ImplementationGuide-markdown-Einwilligungsmanagement-ProfileUndExtensions.html)
    - key-Value Properties könnten eine Extension sein (und nicht n), die durch ein Attribut "Type" welches ein ValueSet (General / n.a., External, Expiration) unterschieden werden
    - VersionFormat Properties könnten eine Extension sein (und nicht n), die durch ein Attribut "Type" welches ein ValueSet (Policy, Module, Template) unterschieden werden
  - [ConsentPolicy](https://www.ths-greifswald.de/wp-content/uploads/tools/fhirgw/ig/ballot-gics/ImplementationGuide-markdown-Einwilligungsmanagement-ProfileUndExtensions-ConsentPolicy.html)
    - einerseits ist es spannend die Policies in Form von FHIR-Ressourcen (ActivityDefinition) zu haben, andererseits gibt es CodeSysteme und ValueSets für diesen Zweck -> das können wir in einer TF CU Sitzung einmal besprechen; käme man nicht mit weniger Extensions in den Ressourcen aus, wenn stattdessen ValueSets verwendet werden, z.B. in [ConsentModule](https://www.ths-greifswald.de/wp-content/uploads/tools/fhirgw/ig/ballot-gics/ImplementationGuide-markdown-Einwilligungsmanagement-ProfileUndExtensions-QuestionnaireProfile-ConsentModule.html). In [Consent](https://www.ths-greifswald.de/wp-content/uploads/tools/fhirgw/ig/ballot-gics/ImplementationGuide-markdown-Einwilligungsmanagement-ProfileUndExtensions-Consent.html) werden dann wieder die Policies aus einem CodeSystem bzw. ValueSet verwendet - diese sollten dann synchron sein, oder? Wie wird das sichergestellt?

Evtl. können einige Exytensions (z.B. Labels, Versionen) über [meta.tag](https://www.hl7.org/fhir/resource-definitions.html) abgebildet werden? MII TF Metadaten kann dazu mehr beitragen.

**Comment by ths-community** [comment]
@SebStaeubert 
- Punkt "Beschreibung": Feedback wurde eingearbeitet in die Ballot-Variante der Beschreibung
- Punkt "Einwilligungsmanagement": Feedback wurde eingearbeitet. Der Absatz "Übersicht der verfügbaren Operations" wurde einheitlich (auch bei Record Linkage und Pseudonymmanagement) entfernt.
- Punkt "Profile und Extensions": für FHIR wird empfohlen Profilierungen eindeutig zu benennen und wenn möglich auf Typisierungen (z.B. unter Verwendung von separaten ValueSets) zu verzichten. Gilt sowohl für die Properties und auch die Versionsangaben.

- Punkt "Labels und Version in meta.tag nutzen": Laut Definition werden die meta.* Inhalte primär intern für serverspezifische Management-zwecke verwendet und sollten von Third Party Systemen entsprechend ignoriert werden. Wir fokussieren jedoch den Informationsaustausch mit Drittsystemen. Daher haben wir separate Datenelemente (z.B. bei Einwilligungsvorlagen) für Label und Version vorgesehen und diese in Extensions verpackt.

**Comment by ths-community** [comment]
Auf Basis der Rückmeldungen erzeugen wir in den kommenden Tagen einen neuen Ballot-Abschluss-IG-Export
