### ISSUE TITLE
Hausnummer nur zusammen mit Straße des Wohnorts in `address.line` 

### ISSUE THREAD

**Issue by makampf** [mosaic-hgw/ttp-fhir-ig#3]
Hausnummer und Straße des Wohnorts können nicht getrennt angegeben werden. Evtl. wäre eine Trennung für manche Auswertungen noch schöner? Ebenso Adresszusatz.
Vgl. auch https://simplifier.net/guide/medizininformatikinitiative-modulperson-implementationguide/PatientInPatient?version=current

evtl. zusammhängend mit https://github.com/mosaic-hgw/ttp-fhir-ig/issues/6

**Comment by noemide** [comment]
Allgemein wäre hier eine Unterstützung des Address-Profiles der deutschen Basisprofile nett (https://ig.fhir.de/basisprofile-de/1.4.0/Ressourcen-Patient-Addresse.html). Das gleiche gilt für Name (https://ig.fhir.de/basisprofile-de/1.4.0/Ressourcen-Patient-Name.html).

**Comment by mosaic-hgw** [comment]
Nicht nötig diese Aufsplittung an dieser Stelle vorzunehmen. Für fTTP und E-PIX ergeben sich rein technisch kein Vorteile durch Trennung dieser Informationen. @noemide patient.family.name und @makampf patient.address.line sind ohnehin zu füllen. Aus diesem Grund werden diese Informationen default-mäßig zum Matching verwendet.
Zukünftig kann man das im Zuge einer möglichen NUM-MII-Konvergenz berücksichtigen und unter #6 weiterverfolgt.
