### ISSUE TITLE
Ist IDAT Profil vollständig?

### ISSUE THREAD

**Issue by makampf** [mosaic-hgw/ttp-fhir-ig#5]
Im Profil befinden sich keine Felder, wie id, identifier, meta und evtl. weitere.
Einige davon sind unten im Beispiel angegeben. Vielleicht ist dargestelltes Profil ein Diff von der Base Resource?
Beispiel unten enthält nicht alle Felder (z.B: nationality fehlt).
Ganz unten steht, es sind keine Extensions definiert - einige werden im Profil jedoch verwendet. Ich weiß nicht, ob die dann unten auch noch einmal gelistet sein müssten.

**Comment by mosaic-hgw** [comment]
Id und meta sind erlaubt und werden im Beispiel nicht gerendert. Identifier wurde bewußt aus Profil entfernt. Nationalität fehlt im Beispiel tatsächlich. Wir vervollständigen das Beispiel entsprechend. Danke für den Hinweis.
