### ISSUE TITLE
MII-Patient für IDAT?

### ISSUE THREAD

**Issue by makampf** [mosaic-hgw/ttp-fhir-ig#6]
Könnte man als IDAT Profil auch gleich den MII Patient verwenden? https://simplifier.net/guide/medizininformatikinitiative-modulperson-implementationguide/PatientInPatient?version=current

**Comment by mosaic-hgw** [comment]
Aktuell spiegelt IDAT-Profil sowohl die IDAT-Elemente wie abgestimmt in MII TF Datenschutz aber auch die im E-PIX persistierten Daten wieder.
Erweiterung in der Zukunft denkbar und möglich im Zuge der MII-NUM-Konvergenz.
