### ISSUE TITLE
Operations: RequestPsnWorkflow

### ISSUE THREAD

**Issue by makampf** [mosaic-hgw/ttp-fhir-ig#7]
https://www.ths-greifswald.de/wp-content/uploads/tools/fhirgw/ig/ballot-fttp/ImplementationGuide-markdown-WorkflowBasierteVerwaltung-Operations-requestPsnWorkflow.html

- Unter Zweck: "Anlegen" groß schreiben
- Unter Zweck: "Parameters" statt "Params"
- Unter Zweck: Bindestrich zwischen "studienspezifischen-Pseudonyme" raus
- Unter Parameters (In): Fehlendes Komma im Satz "Liste studien- und standortspezifischer Originalwerte für die entsprechende Pseudonyme ermittelt bzw. erstellt werden."

**Comment by mosaic-hgw** [comment]
Wir passen den IG entsprechend an. Danke für die detaillierten Hinweise.
