### ISSUE TITLE
Operations: RequestPsnFromBfWorkflow

### ISSUE THREAD

**Issue by makampf** [mosaic-hgw/ttp-fhir-ig#8]
https://www.ths-greifswald.de/wp-content/uploads/tools/fhirgw/ig/ballot-fttp/ImplementationGuide-markdown-WorkflowBasierteVerwaltung-Operations-requestPsnFromBfWorkflow.html

- "Parameters" statt "Params"
- "Die standortspezifische Domäne (target) muss im Zielsystem bekannt und angelegt sein." wobei unter "Zweck" steht, dass diese ggf. auch erst bei Request angelegt wird. Was ist nun korrekt?
- Unter "Parameters (In)": "1. bloomfilter = der zu für PPRL erforderliche Bloomfilter (Teil des Requests)" hier entweder ein "zu" oder ein "für" zu viel im Satz

**Comment by mosaic-hgw** [comment]
@lhitc Es lautet korrekt: "Die standortspezifische Domäne (target) muss im Zielsystem bekannt und angelegt sein." ->Fehlende target-Angabe resultiert in Fehler.
